bot:
  name: ${BOT_NAME}
  key: ${BOT_KEY}
  adminIds: ${BOT_ADMIN}

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: create